# References: 
## https://personality-project.org/r/r.guide.html#oneway
## http://www.gardenersown.co.uk/education/lectures/r/anova.htm
## http://www2.lv.psu.edu/jxm57/irp/chisquar.html

s1.charts.boxplot.easy   <- read.csv("data/boxplots/s1.charts.boxplot.easy.csv")
s1.charts.boxplot.medium <- read.csv("data/boxplots/s1.charts.boxplot.medium.csv")
s1.charts.boxplot.hard   <- read.csv("data/boxplots/s1.charts.boxplot.hard.csv")
s1.dots.boxplot.easy     <- read.csv("data/boxplots/s1.dots.boxplot.easy.csv")
s1.dots.boxplot.medium   <- read.csv("data/boxplots/s1.dots.boxplot.medium.csv")
s1.dots.boxplot.hard     <- read.csv("data/boxplots/s1.dots.boxplot.hard.csv")
s1.series.boxplot.easy   <- read.csv("data/boxplots/s1.series.boxplot.easy.csv")
s1.series.boxplot.medium <- read.csv("data/boxplots/s1.series.boxplot.medium.csv")
s1.series.boxplot.hard   <- read.csv("data/boxplots/s1.series.boxplot.hard.csv")

# Intuitive: 62 users
# Detailed:  56 users
# Compact:   59 users
# Total: 177

s1.charts.boxplot.easy   <- head(s1.charts.boxplot.easy  , 56)
s1.charts.boxplot.medium <- head(s1.charts.boxplot.medium, 56)
s1.charts.boxplot.hard   <- head(s1.charts.boxplot.hard  , 56)
s1.dots.boxplot.easy     <- head(s1.dots.boxplot.easy    , 59)
s1.dots.boxplot.medium   <- head(s1.dots.boxplot.medium  , 59)
s1.dots.boxplot.hard     <- head(s1.dots.boxplot.hard    , 59)
s1.series.boxplot.easy   <- head(s1.series.boxplot.easy  , 62)
s1.series.boxplot.medium <- head(s1.series.boxplot.medium, 62)
s1.series.boxplot.hard   <- head(s1.series.boxplot.hard  , 62)

s2.charts.boxplot.easy   <- read.csv("data/boxplots/s2.charts.boxplot.easy.csv")
s2.charts.boxplot.medium <- read.csv("data/boxplots/s2.charts.boxplot.medium.csv")
s2.charts.boxplot.hard   <- read.csv("data/boxplots/s2.charts.boxplot.hard.csv")
s2.dots.boxplot.easy     <- read.csv("data/boxplots/s2.dots.boxplot.easy.csv")
s2.dots.boxplot.medium   <- read.csv("data/boxplots/s2.dots.boxplot.medium.csv")
s2.dots.boxplot.hard     <- read.csv("data/boxplots/s2.dots.boxplot.hard.csv")
s2.series.boxplot.easy   <- read.csv("data/boxplots/s2.series.boxplot.easy.csv")
s2.series.boxplot.medium <- read.csv("data/boxplots/s2.series.boxplot.medium.csv")
s2.series.boxplot.hard   <- read.csv("data/boxplots/s2.series.boxplot.hard.csv")

# Intuitive: 98 users
# Detailed:  84 users
# Compact:   83 users
# Total: 265

#############################################################
s1.easy.speed <- c()
s1.easy.viz   <- c()
s1.easy.user  <- c()
s1.easy.speed <- c(s1.easy.speed, s1.charts.boxplot.easy$ls.speed)
s1.easy.viz   <- c(s1.easy.viz,   as.vector(s1.charts.boxplot.easy$ls.viz))
s1.easy.user  <- c(s1.easy.user,  as.vector(s1.charts.boxplot.easy$ls.id))
s1.easy.speed <- c(s1.easy.speed, s1.series.boxplot.easy$ls.speed)
s1.easy.viz   <- c(s1.easy.viz,   as.vector(s1.series.boxplot.easy$ls.viz))
s1.easy.user  <- c(s1.easy.user,  as.vector(s1.series.boxplot.easy$ls.id))
s1.easy.speed <- c(s1.easy.speed, s1.dots.boxplot.easy$ls.speed)
s1.easy.viz   <- c(s1.easy.viz,   as.vector(s1.dots.boxplot.easy$ls.viz))
s1.easy.user  <- c(s1.easy.user,  as.vector(s1.dots.boxplot.easy$ls.id))
#############################################################
s1.medium.speed <- c()
s1.medium.viz   <- c()
s1.medium.user  <- c()
s1.medium.speed <- c(s1.medium.speed, s1.charts.boxplot.medium$ls.speed)
s1.medium.viz   <- c(s1.medium.viz,   as.vector(s1.charts.boxplot.medium$ls.viz))
s1.medium.user  <- c(s1.medium.user,  as.vector(s1.charts.boxplot.medium$ls.id))
s1.medium.speed <- c(s1.medium.speed, s1.series.boxplot.medium$ls.speed)
s1.medium.viz   <- c(s1.medium.viz,   as.vector(s1.series.boxplot.medium$ls.viz))
s1.medium.user  <- c(s1.medium.user,  as.vector(s1.series.boxplot.medium$ls.id))
s1.medium.speed <- c(s1.medium.speed, s1.dots.boxplot.medium$ls.speed)
s1.medium.viz   <- c(s1.medium.viz,   as.vector(s1.dots.boxplot.medium$ls.viz))
s1.medium.user  <- c(s1.medium.user,  as.vector(s1.dots.boxplot.medium$ls.id))
#############################################################
s1.hard.speed <- c()
s1.hard.viz   <- c()
s1.hard.user  <- c()
s1.hard.speed <- c(s1.hard.speed, s1.charts.boxplot.hard$ls.speed)
s1.hard.viz   <- c(s1.hard.viz,   as.vector(s1.charts.boxplot.hard$ls.viz))
s1.hard.user  <- c(s1.hard.user,  as.vector(s1.charts.boxplot.hard$ls.id))
s1.hard.speed <- c(s1.hard.speed, s1.series.boxplot.hard$ls.speed)
s1.hard.viz   <- c(s1.hard.viz,   as.vector(s1.series.boxplot.hard$ls.viz))
s1.hard.user  <- c(s1.hard.user,  as.vector(s1.series.boxplot.hard$ls.id))
s1.hard.speed <- c(s1.hard.speed, s1.dots.boxplot.hard$ls.speed)
s1.hard.viz   <- c(s1.hard.viz,   as.vector(s1.dots.boxplot.hard$ls.viz))
s1.hard.user  <- c(s1.hard.user,  as.vector(s1.dots.boxplot.hard$ls.id))
#############################################################
s1.easy.actions <- c()
s1.easy.viz     <- c()
s1.easy.user    <- c()
s1.easy.actions <- c(s1.easy.actions, s1.charts.boxplot.easy$ls.actions)
s1.easy.viz     <- c(s1.easy.viz,     as.vector(s1.charts.boxplot.easy$ls.viz))
s1.easy.user    <- c(s1.easy.user,    as.vector(s1.charts.boxplot.easy$ls.id))
s1.easy.actions <- c(s1.easy.actions, s1.series.boxplot.easy$ls.actions)
s1.easy.viz     <- c(s1.easy.viz,     as.vector(s1.series.boxplot.easy$ls.viz))
s1.easy.user    <- c(s1.easy.user,    as.vector(s1.series.boxplot.easy$ls.id))
s1.easy.actions <- c(s1.easy.actions, s1.dots.boxplot.easy$ls.actions)
s1.easy.viz     <- c(s1.easy.viz,     as.vector(s1.dots.boxplot.easy$ls.viz))
s1.easy.user    <- c(s1.easy.user,    as.vector(s1.dots.boxplot.easy$ls.id))
#############################################################
s1.medium.actions <- c()
s1.medium.viz     <- c()
s1.medium.user    <- c()
s1.medium.actions <- c(s1.medium.actions, s1.charts.boxplot.medium$ls.actions)
s1.medium.viz     <- c(s1.medium.viz,     as.vector(s1.charts.boxplot.medium$ls.viz))
s1.medium.user    <- c(s1.medium.user,    as.vector(s1.charts.boxplot.easy$ls.id))
s1.medium.actions <- c(s1.medium.actions, s1.series.boxplot.medium$ls.actions)
s1.medium.viz     <- c(s1.medium.viz,     as.vector(s1.series.boxplot.medium$ls.viz))
s1.medium.user    <- c(s1.medium.user,    as.vector(s1.series.boxplot.easy$ls.id))
s1.medium.actions <- c(s1.medium.actions, s1.dots.boxplot.medium$ls.actions)
s1.medium.viz     <- c(s1.medium.viz,     as.vector(s1.dots.boxplot.medium$ls.viz))
s1.medium.user    <- c(s1.medium.user,    as.vector(s1.dots.boxplot.easy$ls.id))
#############################################################
s1.hard.actions <- c()
s1.hard.viz     <- c()
s1.hard.user    <- c()
s1.hard.actions <- c(s1.hard.actions, s1.charts.boxplot.hard$ls.actions)
s1.hard.viz     <- c(s1.hard.viz,     as.vector(s1.charts.boxplot.hard$ls.viz))
s1.hard.user    <- c(s1.hard.user,    as.vector(s1.charts.boxplot.easy$ls.id))
s1.hard.actions <- c(s1.hard.actions, s1.series.boxplot.hard$ls.actions)
s1.hard.viz     <- c(s1.hard.viz,     as.vector(s1.series.boxplot.hard$ls.viz))
s1.hard.user    <- c(s1.hard.user,    as.vector(s1.series.boxplot.easy$ls.id))
s1.hard.actions <- c(s1.hard.actions, s1.dots.boxplot.hard$ls.actions)
s1.hard.viz     <- c(s1.hard.viz,     as.vector(s1.dots.boxplot.hard$ls.viz))
s1.hard.user    <- c(s1.hard.user,    as.vector(s1.dots.boxplot.easy$ls.id))
#############################################################
s1.easy.accuracy <- c()
s1.easy.viz     <- c()
s1.easy.user    <- c()
s1.easy.accuracy <- c(s1.easy.accuracy, s1.charts.boxplot.easy$ls.accuracy)
s1.easy.viz     <- c(s1.easy.viz,       as.vector(s1.charts.boxplot.easy$ls.viz))
s1.easy.user    <- c(s1.easy.user,      as.vector(s1.charts.boxplot.easy$ls.id))
s1.easy.accuracy <- c(s1.easy.accuracy, s1.series.boxplot.easy$ls.accuracy)
s1.easy.viz     <- c(s1.easy.viz,       as.vector(s1.series.boxplot.easy$ls.viz))
s1.easy.user    <- c(s1.easy.user,      as.vector(s1.series.boxplot.easy$ls.id))
s1.easy.accuracy <- c(s1.easy.accuracy, s1.dots.boxplot.easy$ls.accuracy)
s1.easy.viz     <- c(s1.easy.viz,       as.vector(s1.dots.boxplot.easy$ls.viz))
s1.easy.user    <- c(s1.easy.user,      as.vector(s1.dots.boxplot.easy$ls.id))
#############################################################
s1.medium.accuracy <- c()
s1.medium.viz     <- c()
s1.medium.user    <- c()
s1.medium.accuracy <- c(s1.medium.accuracy, s1.charts.boxplot.medium$ls.accuracy)
s1.medium.viz     <- c(s1.medium.viz,       as.vector(s1.charts.boxplot.medium$ls.viz))
s1.medium.user    <- c(s1.medium.user,      as.vector(s1.charts.boxplot.medium$ls.id))
s1.medium.accuracy <- c(s1.medium.accuracy, s1.series.boxplot.medium$ls.accuracy)
s1.medium.viz     <- c(s1.medium.viz,       as.vector(s1.series.boxplot.medium$ls.viz))
s1.medium.user    <- c(s1.medium.user,      as.vector(s1.series.boxplot.medium$ls.id))
s1.medium.accuracy <- c(s1.medium.accuracy, s1.dots.boxplot.medium$ls.accuracy)
s1.medium.viz     <- c(s1.medium.viz,       as.vector(s1.dots.boxplot.medium$ls.viz))
s1.medium.user    <- c(s1.medium.user,      as.vector(s1.dots.boxplot.medium$ls.id))
#############################################################
s1.hard.accuracy <- c()
s1.hard.viz     <- c()
s1.hard.user    <- c()
s1.hard.accuracy <- c(s1.hard.accuracy, s1.charts.boxplot.hard$ls.accuracy)
s1.hard.viz     <- c(s1.hard.viz,       as.vector(s1.charts.boxplot.hard$ls.viz))
s1.hard.user    <- c(s1.hard.user,      as.vector(s1.charts.boxplot.hard$ls.id))
s1.hard.accuracy <- c(s1.hard.accuracy, s1.series.boxplot.hard$ls.accuracy)
s1.hard.viz     <- c(s1.hard.viz,       as.vector(s1.series.boxplot.hard$ls.viz))
s1.hard.user    <- c(s1.hard.user,      as.vector(s1.series.boxplot.hard$ls.id))
s1.hard.accuracy <- c(s1.hard.accuracy, s1.dots.boxplot.hard$ls.accuracy)
s1.hard.viz     <- c(s1.hard.viz,       as.vector(s1.dots.boxplot.hard$ls.viz))
s1.hard.user    <- c(s1.hard.user,      as.vector(s1.dots.boxplot.hard$ls.id))
#############################################################

#############################################################
s2.easy.speed <- c()
s2.easy.viz   <- c()
s2.easy.user  <- c()
s2.easy.speed <- c(s2.easy.speed, s2.charts.boxplot.easy$ls.speed)
s2.easy.viz   <- c(s2.easy.viz,   as.vector(s2.charts.boxplot.easy$ls.viz))
s2.easy.user  <- c(s2.easy.user,  as.vector(s2.charts.boxplot.easy$ls.id))
s2.easy.speed <- c(s2.easy.speed, s2.series.boxplot.easy$ls.speed)
s2.easy.viz   <- c(s2.easy.viz,   as.vector(s2.series.boxplot.easy$ls.viz))
s2.easy.user  <- c(s2.easy.user,  as.vector(s2.series.boxplot.easy$ls.id))
s2.easy.speed <- c(s2.easy.speed, s2.dots.boxplot.easy$ls.speed)
s2.easy.viz   <- c(s2.easy.viz,   as.vector(s2.dots.boxplot.easy$ls.viz))
s2.easy.user  <- c(s2.easy.user,  as.vector(s2.dots.boxplot.easy$ls.id))
#############################################################
s2.medium.speed <- c()
s2.medium.viz   <- c()
s2.medium.user  <- c()
s2.medium.speed <- c(s2.medium.speed, s2.charts.boxplot.medium$ls.speed)
s2.medium.viz   <- c(s2.medium.viz,   as.vector(s2.charts.boxplot.medium$ls.viz))
s2.medium.user  <- c(s2.medium.user,  as.vector(s2.charts.boxplot.medium$ls.id))
s2.medium.speed <- c(s2.medium.speed, s2.series.boxplot.medium$ls.speed)
s2.medium.viz   <- c(s2.medium.viz,   as.vector(s2.series.boxplot.medium$ls.viz))
s2.medium.user  <- c(s2.medium.user,  as.vector(s2.series.boxplot.medium$ls.id))
s2.medium.speed <- c(s2.medium.speed, s2.dots.boxplot.medium$ls.speed)
s2.medium.viz   <- c(s2.medium.viz,   as.vector(s2.dots.boxplot.medium$ls.viz))
s2.medium.user  <- c(s2.medium.user,  as.vector(s2.dots.boxplot.medium$ls.id))
#############################################################
s2.hard.speed <- c()
s2.hard.viz   <- c()
s2.hard.user  <- c()
s2.hard.speed <- c(s2.hard.speed, s2.charts.boxplot.hard$ls.speed)
s2.hard.viz   <- c(s2.hard.viz,   as.vector(s2.charts.boxplot.hard$ls.viz))
s2.hard.user  <- c(s2.hard.user,  as.vector(s2.charts.boxplot.hard$ls.id))
s2.hard.speed <- c(s2.hard.speed, s2.series.boxplot.hard$ls.speed)
s2.hard.viz   <- c(s2.hard.viz,   as.vector(s2.series.boxplot.hard$ls.viz))
s2.hard.user  <- c(s2.hard.user,  as.vector(s2.series.boxplot.hard$ls.id))
s2.hard.speed <- c(s2.hard.speed, s2.dots.boxplot.hard$ls.speed)
s2.hard.viz   <- c(s2.hard.viz,   as.vector(s2.dots.boxplot.hard$ls.viz))
s2.hard.user  <- c(s2.hard.user,  as.vector(s2.dots.boxplot.hard$ls.id))
#############################################################
s2.easy.actions <- c()
s2.easy.viz     <- c()
s2.easy.user    <- c()
s2.easy.actions <- c(s2.easy.actions, s2.charts.boxplot.easy$ls.actions)
s2.easy.viz     <- c(s2.easy.viz,     as.vector(s2.charts.boxplot.easy$ls.viz))
s2.easy.user    <- c(s2.easy.user,    as.vector(s2.charts.boxplot.easy$ls.id))
s2.easy.actions <- c(s2.easy.actions, s2.series.boxplot.easy$ls.actions)
s2.easy.viz     <- c(s2.easy.viz,     as.vector(s2.series.boxplot.easy$ls.viz))
s2.easy.user    <- c(s2.easy.user,    as.vector(s2.series.boxplot.easy$ls.id))
s2.easy.actions <- c(s2.easy.actions, s2.dots.boxplot.easy$ls.actions)
s2.easy.viz     <- c(s2.easy.viz,     as.vector(s2.dots.boxplot.easy$ls.viz))
s2.easy.user    <- c(s2.easy.user,    as.vector(s2.dots.boxplot.easy$ls.id))
#############################################################
s2.medium.actions <- c()
s2.medium.viz     <- c()
s2.medium.user    <- c()
s2.medium.actions <- c(s2.medium.actions, s2.charts.boxplot.medium$ls.actions)
s2.medium.viz     <- c(s2.medium.viz,     as.vector(s2.charts.boxplot.medium$ls.viz))
s2.medium.user    <- c(s2.medium.user,    as.vector(s2.charts.boxplot.easy$ls.id))
s2.medium.actions <- c(s2.medium.actions, s2.series.boxplot.medium$ls.actions)
s2.medium.viz     <- c(s2.medium.viz,     as.vector(s2.series.boxplot.medium$ls.viz))
s2.medium.user    <- c(s2.medium.user,    as.vector(s2.series.boxplot.easy$ls.id))
s2.medium.actions <- c(s2.medium.actions, s2.dots.boxplot.medium$ls.actions)
s2.medium.viz     <- c(s2.medium.viz,     as.vector(s2.dots.boxplot.medium$ls.viz))
s2.medium.user    <- c(s2.medium.user,    as.vector(s2.dots.boxplot.easy$ls.id))
#############################################################
s2.hard.actions <- c()
s2.hard.viz     <- c()
s2.hard.user    <- c()
s2.hard.actions <- c(s2.hard.actions, s2.charts.boxplot.hard$ls.actions)
s2.hard.viz     <- c(s2.hard.viz,     as.vector(s2.charts.boxplot.hard$ls.viz))
s2.hard.user    <- c(s2.hard.user,    as.vector(s2.charts.boxplot.easy$ls.id))
s2.hard.actions <- c(s2.hard.actions, s2.series.boxplot.hard$ls.actions)
s2.hard.viz     <- c(s2.hard.viz,     as.vector(s2.series.boxplot.hard$ls.viz))
s2.hard.user    <- c(s2.hard.user,    as.vector(s2.series.boxplot.easy$ls.id))
s2.hard.actions <- c(s2.hard.actions, s2.dots.boxplot.hard$ls.actions)
s2.hard.viz     <- c(s2.hard.viz,     as.vector(s2.dots.boxplot.hard$ls.viz))
s2.hard.user    <- c(s2.hard.user,    as.vector(s2.dots.boxplot.easy$ls.id))
#############################################################
s2.easy.accuracy <- c()
s2.easy.viz     <- c()
s2.easy.user    <- c()
s2.easy.accuracy <- c(s2.easy.accuracy, s2.charts.boxplot.easy$ls.accuracy)
s2.easy.viz     <- c(s2.easy.viz,       as.vector(s2.charts.boxplot.easy$ls.viz))
s2.easy.user    <- c(s2.easy.user,      as.vector(s2.charts.boxplot.easy$ls.id))
s2.easy.accuracy <- c(s2.easy.accuracy, s2.series.boxplot.easy$ls.accuracy)
s2.easy.viz     <- c(s2.easy.viz,       as.vector(s2.series.boxplot.easy$ls.viz))
s2.easy.user    <- c(s2.easy.user,      as.vector(s2.series.boxplot.easy$ls.id))
s2.easy.accuracy <- c(s2.easy.accuracy, s2.dots.boxplot.easy$ls.accuracy)
s2.easy.viz     <- c(s2.easy.viz,       as.vector(s2.dots.boxplot.easy$ls.viz))
s2.easy.user    <- c(s2.easy.user,      as.vector(s2.dots.boxplot.easy$ls.id))
#############################################################
s2.medium.accuracy <- c()
s2.medium.viz     <- c()
s2.medium.user    <- c()
s2.medium.accuracy <- c(s2.medium.accuracy, s2.charts.boxplot.medium$ls.accuracy)
s2.medium.viz     <- c(s2.medium.viz,       as.vector(s2.charts.boxplot.medium$ls.viz))
s2.medium.user    <- c(s2.medium.user,      as.vector(s2.charts.boxplot.medium$ls.id))
s2.medium.accuracy <- c(s2.medium.accuracy, s2.series.boxplot.medium$ls.accuracy)
s2.medium.viz     <- c(s2.medium.viz,       as.vector(s2.series.boxplot.medium$ls.viz))
s2.medium.user    <- c(s2.medium.user,      as.vector(s2.series.boxplot.medium$ls.id))
s2.medium.accuracy <- c(s2.medium.accuracy, s2.dots.boxplot.medium$ls.accuracy)
s2.medium.viz     <- c(s2.medium.viz,       as.vector(s2.dots.boxplot.medium$ls.viz))
s2.medium.user    <- c(s2.medium.user,      as.vector(s2.dots.boxplot.medium$ls.id))
#############################################################
s2.hard.accuracy <- c()
s2.hard.viz     <- c()
s2.hard.user    <- c()
s2.hard.accuracy <- c(s2.hard.accuracy, s2.charts.boxplot.hard$ls.accuracy)
s2.hard.viz     <- c(s2.hard.viz,       as.vector(s2.charts.boxplot.hard$ls.viz))
s2.hard.user    <- c(s2.hard.user,      as.vector(s2.charts.boxplot.hard$ls.id))
s2.hard.accuracy <- c(s2.hard.accuracy, s2.series.boxplot.hard$ls.accuracy)
s2.hard.viz     <- c(s2.hard.viz,       as.vector(s2.series.boxplot.hard$ls.viz))
s2.hard.user    <- c(s2.hard.user,      as.vector(s2.series.boxplot.hard$ls.id))
s2.hard.accuracy <- c(s2.hard.accuracy, s2.dots.boxplot.hard$ls.accuracy)
s2.hard.viz     <- c(s2.hard.viz,       as.vector(s2.dots.boxplot.hard$ls.viz))
s2.hard.user    <- c(s2.hard.user,      as.vector(s2.dots.boxplot.hard$ls.id))
#############################################################


s1.df.speed.easy      <- data.frame(s1.easy.user,   s1.easy.viz,   s1.easy.speed) 
s1.df.speed.medium    <- data.frame(s1.medium.user, s1.medium.viz, s1.medium.speed) 
s1.df.speed.hard      <- data.frame(s1.hard.user,   s1.hard.viz,   s1.hard.speed) 
s1.df.actions.easy    <- data.frame(s1.easy.user,   s1.easy.viz,   s1.easy.actions) 
s1.df.actions.medium  <- data.frame(s1.medium.user, s1.medium.viz, s1.medium.actions) 
s1.df.actions.hard    <- data.frame(s1.hard.user,   s1.hard.viz,   s1.hard.actions) 
s1.df.accuracy.easy   <- data.frame(s1.easy.user,   s1.easy.viz,   s1.easy.accuracy) 
s1.df.accuracy.medium <- data.frame(s1.medium.user, s1.medium.viz, s1.medium.accuracy) 
s1.df.accuracy.hard   <- data.frame(s1.hard.user,   s1.hard.viz,   s1.hard.accuracy) 

s2.df.speed.easy      <- data.frame(s2.easy.user,   s2.easy.viz,   s2.easy.speed) 
s2.df.speed.medium    <- data.frame(s2.medium.user, s2.medium.viz, s2.medium.speed) 
s2.df.speed.hard      <- data.frame(s2.hard.user,   s2.hard.viz,   s2.hard.speed) 
s2.df.actions.easy    <- data.frame(s2.easy.user,   s2.easy.viz,   s2.easy.actions) 
s2.df.actions.medium  <- data.frame(s2.medium.user, s2.medium.viz, s2.medium.actions) 
s2.df.actions.hard    <- data.frame(s2.hard.user,   s2.hard.viz,   s2.hard.actions) 
s2.df.accuracy.easy   <- data.frame(s2.easy.user,   s2.easy.viz,   s2.easy.accuracy) 
s2.df.accuracy.medium <- data.frame(s2.medium.user, s2.medium.viz, s2.medium.accuracy) 
s2.df.accuracy.hard   <- data.frame(s2.hard.user,   s2.hard.viz,   s2.hard.accuracy) 

s1.df.accuracy.easy["difficulty"]   <- rep(factor("easy"),   177)
s1.df.accuracy.medium["difficulty"] <- rep(factor("medium"), 177)
s1.df.accuracy.hard["difficulty"]   <- rep(factor("hard"),   177)
s1.df.actions.easy["difficulty"]    <- rep(factor("easy"),   177)
s1.df.actions.medium["difficulty"]  <- rep(factor("medium"), 177)
s1.df.actions.hard["difficulty"]    <- rep(factor("hard"),   177)
s1.df.speed.easy["difficulty"]      <- rep(factor("easy"),   177)
s1.df.speed.medium["difficulty"]    <- rep(factor("medium"), 177)
s1.df.speed.hard["difficulty"]      <- rep(factor("hard"),   177)

#s1.df.accuracy.easy["study"]   <- rep(factor("s1"),211)
#s1.df.accuracy.medium["study"] <- rep(factor("s1"),211)
#s1.df.accuracy.hard["study"]   <- rep(factor("s1"),211)
#s1.df.actions.easy["study"]    <- rep(factor("s1"),211)
#s1.df.actions.medium["study"]  <- rep(factor("s1"),211)
#s1.df.actions.hard["study"]    <- rep(factor("s1"),211)
#s1.df.speed.easy["study"]      <- rep(factor("s1"),211)
#s1.df.speed.medium["study"]    <- rep(factor("s1"),211)
#s1.df.speed.hard["study"]      <- rep(factor("s1"),211)

s2.df.accuracy.easy["difficulty"]   <- rep(factor("easy"),   265)
s2.df.accuracy.medium["difficulty"] <- rep(factor("medium"), 265)
s2.df.accuracy.hard["difficulty"]   <- rep(factor("hard"),   265)
s2.df.actions.easy["difficulty"]    <- rep(factor("easy"),   265)
s2.df.actions.medium["difficulty"]  <- rep(factor("medium"), 265)
s2.df.actions.hard["difficulty"]    <- rep(factor("hard"),   265)
s2.df.speed.easy["difficulty"]      <- rep(factor("easy"),   265)
s2.df.speed.medium["difficulty"]    <- rep(factor("medium"), 265)
s2.df.speed.hard["difficulty"]      <- rep(factor("hard"),   265)

#s2.df.accuracy.easy["study"]   <- rep(factor("s2"),265)
#s2.df.accuracy.medium["study"] <- rep(factor("s2"),265)
#s2.df.accuracy.hard["study"]   <- rep(factor("s2"),265)
#s2.df.actions.easy["study"]    <- rep(factor("s2"),265)
#s2.df.actions.medium["study"]  <- rep(factor("s2"),265)
#s2.df.actions.hard["study"]    <- rep(factor("s2"),265)
#s2.df.speed.easy["study"]      <- rep(factor("s2"),265)
#s2.df.speed.medium["study"]    <- rep(factor("s2"),265)
#s2.df.speed.hard["study"]      <- rep(factor("s2"),265)

colnames(s1.df.accuracy.easy)       <- c("user","viz", "accuracy", "difficulty")#, "study")
colnames(s1.df.accuracy.medium)     <- c("user","viz", "accuracy", "difficulty")#, "study")
colnames(s1.df.accuracy.hard)       <- c("user","viz", "accuracy", "difficulty")#, "study")
colnames(s1.df.actions.easy)        <- c("user","viz", "actions",  "difficulty")#, "study")
colnames(s1.df.actions.medium)      <- c("user","viz", "actions",  "difficulty")#, "study")
colnames(s1.df.actions.hard)        <- c("user","viz", "actions",  "difficulty")#, "study")
colnames(s1.df.speed.easy)          <- c("user","viz", "speed",    "difficulty")#, "study")
colnames(s1.df.speed.medium)        <- c("user","viz", "speed",    "difficulty")#, "study")
colnames(s1.df.speed.hard)          <- c("user","viz", "speed",    "difficulty")#, "study")

colnames(s2.df.accuracy.easy)       <- c("user","viz", "accuracy", "difficulty")#,  "study")
colnames(s2.df.accuracy.medium)     <- c("user","viz", "accuracy", "difficulty")#,  "study")
colnames(s2.df.accuracy.hard)       <- c("user","viz", "accuracy", "difficulty")#,  "study")
colnames(s2.df.actions.easy)        <- c("user","viz", "actions",  "difficulty")#,  "study")
colnames(s2.df.actions.medium)      <- c("user","viz", "actions",  "difficulty")#,  "study")
colnames(s2.df.actions.hard)        <- c("user","viz", "actions",  "difficulty")#,  "study")
colnames(s2.df.speed.easy)          <- c("user","viz", "speed",    "difficulty")#,  "study")
colnames(s2.df.speed.medium)        <- c("user","viz", "speed",    "difficulty")#,  "study")
colnames(s2.df.speed.hard)          <- c("user","viz", "speed",    "difficulty")#,  "study")

s1.df.accuracy.all <- rbind(s1.df.accuracy.easy, s1.df.accuracy.medium, s1.df.accuracy.hard)
s1.df.actions.all  <- rbind(s1.df.actions.easy,  s1.df.actions.medium,  s1.df.actions.hard )
s1.df.speed.all    <- rbind(s1.df.speed.easy,    s1.df.speed.medium,    s1.df.speed.hard   )
s2.df.accuracy.all <- rbind(s2.df.accuracy.easy, s2.df.accuracy.medium, s2.df.accuracy.hard)
s2.df.actions.all  <- rbind(s2.df.actions.easy,  s2.df.actions.medium,  s2.df.actions.hard )
s2.df.speed.all    <- rbind(s2.df.speed.easy,    s2.df.speed.medium,    s2.df.speed.hard   )

write.csv(s1.df.accuracy.all, file = "s1.df.accuracy.all.csv", row.names=FALSE)
write.csv(s1.df.actions.all,  file = "s1.df.actions.all.csv" , row.names=FALSE)
write.csv(s1.df.speed.all,    file = "s1.df.speed.all.csv"   , row.names=FALSE)
write.csv(s2.df.accuracy.all, file = "s2.df.accuracy.all.csv", row.names=FALSE)
write.csv(s2.df.actions.all,  file = "s2.df.actions.all.csv" , row.names=FALSE)
write.csv(s2.df.speed.all,    file = "s2.df.speed.all.csv"   , row.names=FALSE)

# df.accuracy.all <- rbind(s1.df.accuracy.all, s2.df.accuracy.all)
# df.actions.all  <- rbind(s1.df.actions.all,  s2.df.actions.all)
# df.speed.all    <- rbind(s1.df.speed.all,    s2.df.speed.all)

# three.accuracy.out <- aov(accuracy~viz*difficulty*study, data = df.accuracy.all)
# TukeyHSD(three.accuracy.out, which="difficulty")
# TukeyHSD(three.accuracy.out, which="viz")
# TukeyHSD(three.accuracy.out, which="study")
# TukeyHSD(three.accuracy.out)

# s1.accuracy.out <- aov(accuracy ~ viz * difficulty, data=s1.df.accuracy.all)
# s1.actions.out  <- aov(actions  ~ viz * difficulty, data=s1.df.actions.all)
# s1.speed.out    <- aov(speed    ~ viz * difficulty, data=s1.df.speed.all)
# 
# s2.accuracy.out <- aov(accuracy ~ viz * difficulty, data=s2.df.accuracy.all)
# s2.actions.out  <- aov(actions  ~ viz * difficulty, data=s2.df.actions.all)
# s2.speed.out    <- aov(speed    ~ viz * difficulty, data=s2.df.speed.all)

# summary(actions.out)
# TukeyHSD(actions.out)
# summary(accuracy.out)
# TukeyHSD(accuracy.out)
# summary(speed.out)
# TukeyHSD(speed.out)

#mean(s1.series.boxplot.easy$ls.speed  )
#mean(s1.charts.boxplot.easy$ls.speed  )
#mean(s1.dots.boxplot.easy$ls.speed    )
#mean(s1.series.boxplot.medium$ls.speed)
#mean(s1.charts.boxplot.medium$ls.speed)
#mean(s1.dots.boxplot.medium$ls.speed  )
#mean(s1.series.boxplot.hard$ls.speed  )
#mean(s1.charts.boxplot.hard$ls.speed  )
#mean(s1.dots.boxplot.hard$ls.speed    )
#
#mean(s2.series.boxplot.easy$ls.speed   )
#mean(s2.charts.boxplot.easy$ls.speed   )
#mean(s2.dots.boxplot.easy$ls.speed     )
#mean(s2.series.boxplot.medium$ls.speed )
#mean(s2.charts.boxplot.medium$ls.speed )
#mean(s2.dots.boxplot.medium$ls.speed   )
#mean(s2.series.boxplot.hard$ls.speed   )
#mean(s2.charts.boxplot.hard$ls.speed   )
#mean(s2.dots.boxplot.hard$ls.speed     )


